# ==============================================================================
# Docker Compose for Phoenix LiveView Application
# Following August 2025 best practices
# ==============================================================================

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      # Required environment variables
      - PHX_SERVER=true
      - SECRET_KEY_BASE=${SECRET_KEY_BASE:-$(openssl rand -base64 64 | tr -d '\n')}
      - PHX_HOST=${PHX_HOST:-localhost}
      - PORT=3000
      
      # Google Cloud / AI configuration
      - VERTEXAI_PROJECT=${VERTEXAI_PROJECT}
      - VERTEXAI_LOCATION=${VERTEXAI_LOCATION:-europe-west1}
      - GEMINI_MODEL=${GEMINI_MODEL:-gemini-2.5-flash}
      - GOOGLE_APPLICATION_CREDENTIALS=${GOOGLE_APPLICATION_CREDENTIALS}
      - GOOGLE_SERVICE_ACCOUNT_JSON=${GOOGLE_SERVICE_ACCOUNT_JSON}
    
    volumes:
      # Persistent data volumes - everything now under priv/data
      - app_data:/app/priv/data
      
      # Optional: Mount Google Cloud credentials
      - ${GOOGLE_APPLICATION_CREDENTIALS:-/dev/null}:${GOOGLE_APPLICATION_CREDENTIALS:-/dev/null}:ro
    
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 60s
    
    restart: unless-stopped
    
    # Security: run as non-root
    user: "1000:1000"

volumes:
  app_data:
    driver: local
