defmodule LiveAiChatWeb.AuthControllerTest do
  use LiveAiChatWeb.ConnCase, async: true

  describe "logout" do
    test "clears session and redirects to home", %{conn: conn} do
      user = %{sub: "123", email: "test@example.com", name: "Test User"}

      conn =
        conn
        |> init_test_session(%{user: user})
        |> post(~p"/auth/logout")

      assert redirected_to(conn) == "/"
      assert Phoenix.Flash.get(conn.assigns.flash, :info) == "You have been logged out."
      # In test, just verify the endpoint was called correctly
    end
  end

  describe "request" do
    test "redirects to Google OAuth", %{conn: conn} do
      conn = get(conn, ~p"/auth/google")

      assert conn.status == 302
      # The exact redirect URL will be generated by Ueberauth
      assert get_resp_header(conn, "location") != []
    end
  end
end
